/**
 * Audience-specific heat advisories, generated deterministically from a snapshot and the engine's analysis.
 * Guidance follows India's national heat-wave action guidelines (NDMA) and IMD's colour-coded warnings. Every draft
 * is marked as a draft until a person approves it — the human-in-the-loop step the use case requires.
 */
import { DISTRICTS, type Snapshot } from './data';
import type { Intel } from './engine';
import { LEVELS, type Level } from './heat';
import { fmtDay } from './utils';

export type Audience = 'citizens' | 'farmers' | 'health' | 'authorities';

export const AUDIENCES: { id: Audience; label: string; blurb: string }[] = [
  { id: 'citizens', label: 'Citizens', blurb: 'Plain language, what to do today' },
  { id: 'farmers', label: 'Farmers', blurb: 'Field work, irrigation, livestock' },
  { id: 'health', label: 'Health', blurb: 'Hospitals, PHCs, ambulances' },
  { id: 'authorities', label: 'Authorities', blurb: 'District control rooms, SDMA' },
];

export interface Advisory {
  audience: Audience;
  level: Level;
  headline: string;
  summary: string;
  actions: string[];
  districts: number[];
  footer: string;
}

const names = (ids: number[], max = 6) => {
  const list = ids.slice(0, max).map((i) => DISTRICTS[i].name);
  const more = ids.length - list.length;
  if (list.length === 0) return 'no district';
  if (list.length === 1) return list[0];
  return more > 0 ? `${list.join(', ')} and ${more} more` : `${list.slice(0, -1).join(', ')} and ${list[list.length - 1]}`;
};

export function generateAdvisory(s: Snapshot, intel: Intel, audience: Audience): Advisory {
  const byLevel = (l: Level) => intel.ranking.filter((id) => s.rows[id].status.level === l);
  const red = byLevel('red');
  const orange = byLevel('orange');
  const yellow = byLevel('yellow');
  const warned = [...red, ...orange];
  const top = s.rows[intel.ranking[0]];
  const level: Level = red.length ? 'red' : orange.length ? 'orange' : yellow.length ? 'yellow' : 'green';
  const day = fmtDay(s.day);
  const biggest = intel.clusters[0] ?? [];
  const footer =
    s.mode === 'replay'
      ? `Draft generated by HEATSYNC from ERA5 reanalysis for ${day} (historical replay). Not an official IMD warning — requires approval before release.`
      : `Draft generated by HEATSYNC from Open-Meteo guidance for ${day}. Not an official IMD warning — requires approval before release.`;

  if (level === 'green') {
    return {
      audience,
      level,
      headline: `No heat warning for Maharashtra on ${day}`,
      summary: `All 36 districts are below the heat thresholds. The hottest is ${DISTRICTS[top.id].name} at ${top.tmax.toFixed(1)} °C.`,
      actions: ['Keep drinking water through the day.', 'Watch the next bulletin: conditions can change within 24 hours.'],
      districts: [],
      footer,
    };
  }

  const lead = `${LEVELS[level].label}${warned.length ? ` in ${names(warned)}` : ''}`;
  const watchLine = yellow.length ? ` Heat watch in ${names(yellow, 5)}.` : '';
  const peak = `${DISTRICTS[top.id].name} is the hottest at ${top.tmax.toFixed(1)} °C`;

  switch (audience) {
    case 'citizens':
      return {
        audience,
        level,
        headline: `${lead} — ${day}`,
        summary: `${peak}.${watchLine} Stay out of direct sun between 12 noon and 3 pm.`,
        actions: [
          'Drink water often, even if you are not thirsty. Use ORS, lassi, buttermilk or lemon water.',
          'Wear light, loose cotton clothes and cover your head with a cap, cloth or umbrella outdoors.',
          'Check twice a day on elderly neighbours, young children and anyone living alone.',
          'Never leave children or pets in a parked vehicle.',
          'Dizziness, confusion, hot dry skin or fainting can be heat stroke: call 108 and cool the person immediately.',
        ],
        districts: [...warned, ...yellow],
        footer,
      };
    case 'farmers':
      return {
        audience,
        level,
        headline: `Farm heat advisory — ${day}`,
        summary: `${peak}. Heat stress is highest for workers, livestock and standing crops in ${names([...warned, ...yellow], 5)}.`,
        actions: [
          'Shift field work to early morning and late evening; rest in shade between 12 noon and 3 pm.',
          'Give light, frequent irrigation in the evening; mulch to keep soil moisture in.',
          'Keep livestock in shade with plenty of clean drinking water; do not graze them in the afternoon.',
          'Avoid spraying pesticides or fertilisers in the afternoon heat.',
          'Keep drinking water and ORS at the field for every worker.',
        ],
        districts: [...warned, ...yellow],
        footer,
      };
    case 'health':
      return {
        audience,
        level,
        headline: `Health system alert — ${day}`,
        summary: `${warned.length || yellow.length} districts at watch level or above; the largest contiguous hot zone spans ${biggest.length} districts (${names(biggest, 4)}).`,
        actions: [
          `Activate heat-stroke rooms with cooling beds in district and sub-district hospitals in ${names(warned.length ? warned : yellow, 5)}.`,
          'Stock ORS, IV fluids and ice packs at PHCs; pre-position ambulances on 108 routes.',
          'Triage heat illness first: rapid cooling for core-temperature emergencies.',
          'Record every suspected heat-related illness and death in the daily surveillance report.',
          `Share the alert with neighbouring districts on the first alert ring: ${names(intel.rings[1] ?? [], 5)}.`,
        ],
        districts: [...warned, ...yellow],
        footer,
      };
    case 'authorities': {
      const staging = intel.relief
        .filter((r) => r.path && r.path.length > 1)
        .slice(0, 3)
        .map((r) => `${DISTRICTS[r.from].name} ← ${DISTRICTS[r.path![r.path!.length - 1]].name} (${r.path!.length - 1} hop${r.path!.length > 2 ? 's' : ''})`);
      return {
        audience,
        level,
        headline: `District control rooms: ${lead}`,
        summary: `${peak}. ${intel.clusters.length} contiguous hot zone${intel.clusters.length === 1 ? '' : 's'} detected across shared borders.`,
        actions: [
          'Open cooling shelters and drinking-water points along markets, bus stands and construction sites.',
          'Reschedule outdoor work (construction, MGNREGA, traffic duty) away from 12 noon – 3 pm.',
          'Run water tankers to areas with known supply gaps; keep fire services on standby.',
          staging.length ? `Stage relief supplies from the nearest cooler district: ${staging.join('; ')}.` : 'All hot districts are surrounded by hot districts: stage relief from state reserves.',
          `Coordinate with the first alert ring (${names(intel.rings[1] ?? [], 5)}) before the heat spreads further.`,
        ],
        districts: [...warned, ...yellow],
        footer,
      };
    }
  }
}
